server:
  port: 8081
spring:
  application:
    name: itemservice
    profiles:
      active: test
  datasource:
    url: jdbc:mysql://${power.mysql.ip}:${power.mysql.port}/${power.mysql.db}?useSSL=false
    username: ${power.mysql.username}
    password: ${power.mysql.password}
    driver-class-name: com.mysql.jdbc.Driver
mybatis-plus:
  type-aliases-package: com.heima.item.pojo
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      update-strategy: not_null
      id-type: auto
logging:
  level:
    com.heima: debug
  pattern:
    dateformat: HH:mm:ss:SSS